---
extends: default

rules:
  line-length:
    max: 120
    level: warning
  
  comments:
    min-spaces-from-content: 1
  
  comments-indentation: disable
  
  document-start:
    present: false
  
  indentation:
    spaces: 2
    indent-sequences: true
    check-multi-line-strings: false
  
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no', 'on', 'off']
    level: warning
  
  brackets:
    max-spaces-inside: 1
  
  braces:
    max-spaces-inside: 1
  
  empty-lines:
    max: 2
    max-start: 0
    max-end: 0

ignore: |
  node_modules/
  vendor/
  .git/
  *.generated.yml